services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_DATABASE: books
      MYSQL_ROOT_PASSWORD: passsword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
#    volumes:
#      - ./mysqlconfig/:/docker-entrypoint-initdb.d/
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10